### ISSUE TITLE
Mark classes and mark sets are not merged correctly

### ISSUE THREAD

**Issue by dscorbett** [satbyy/go-noto-universal#3]
Fonts with lookups that use mark classes or mark sets are not merged correctly. If, say, a lookup in a source font uses mark set 0, the corresponding lookup in the merged font will also use mark set 0, even though the merged font’s mark set 0 might come from a different source font.

For example, here is <U+11C72, U+11C92, U+11C93> in Go Noto East Asia:
![𑱲𑲒𑲓](https://user-images.githubusercontent.com/1124347/145932484-4da07c1a-8539-4438-a4b8-a3a3efea8bf3.png)
And here it is in Noto Sans Marchen:
![𑱲𑲒𑲓](https://user-images.githubusercontent.com/1124347/145932556-feb7b6f1-6bf3-45ee-86dd-505839c5eecb.png)

**Comment by satbyy** [comment]
Interesting bug! This are is somewhat unfamiliar to me. I get the same results with bare `pyftmerge`. So probably reporting to [fonttools/fonttools](https://github.com/fonttools/fonttools) might be better.

**Comment by dscorbett** [comment]
It is fonttools/fonttools#1260. It’s not related to line metrics.
