### ISSUE TITLE
Latest upstream Tibetan serif breaks build 

### ISSUE THREAD

**Issue by satbyy** [satbyy/go-noto-universal#34]
[This commit](https://github.com/googlefonts/noto-fonts/commit/404f9f1a7a3929c939cb566d249b9477f24d18cb) traced to [this source](https://github.com/googlefonts/noto-source/commit/dfe78a538d2515dec22bf40db3c596457b47df50) breaks all the "Go Noto" fonts involving Tibetan.

**Comment by dscorbett** [comment]
Does excluding `.3`-suffixed glyphs help, as suggested in dcd76491c0618eefe095c004736aed738d63e9d3?
