### ISSUE TITLE
Request for other weight

### ISSUE THREAD

**Issue by podhikaru** [satbyy/go-noto-universal#5]
I used "GoNotoSouthEastAsia" with in Thai. That work perfectly but I can't find other weight like Thin, Semi Bold, Bold, ect.
can you add other weight or how to compile it. that would be great.

thank you for build this project.

**Comment by satbyy** [comment]
I agree your idea, yes. However, not all the font weights are available for all the scripts. They exist for popular languages like Thai, Lao or Khmer but missing for, say, Javanese. So a "South East Asia - Thin" variant ends up omitting much of SE Asia.

Maybe only the Bold weight is possible. Someone (or I) could check it when time permits.

**Comment by dweymouth** [comment]
Also would love to have a bold weight version of GoNotoCurrent.ttf
