### ISSUE TITLE
Add Ge'ez (Ethiopic) script fonts

### ISSUE THREAD

**Issue by quantum9Innovation** [satbyy/go-noto-universal#56]
Under ["Africa Middle East"](https://github.com/satbyy/go-noto-universal#go-noto-africa-middle-east), the languages listed are:
> Adlam, Anatolian Hieroglyphics, Arabic (Naskh-style), Avestan, Bamum, Bassa Vah, Chorasmian, Cuneiform, Egyptian, Elymaic, Hatran, Hebrew, Imperial Aramaic, Inscriptional Pahlavi, Inscriptional Parthian, Mandaic, Manichaean, Meroitic, Nabataean, Old North Arabian, Old Persian, Old South Arabian, Palmyrene, Phoenician, Psalter Pahlavi, Samaritan, Syriac, Ugaritic, Yezidi.

This doesn't include the Ge'ez script for Ethiopic languages.
The relevant Noto fonts for [serif](https://fonts.google.com/noto/specimen/Noto+Serif+Ethiopic) and [sans-serif](https://fonts.google.com/noto/specimen/Noto+Sans+Ethiopic) are linked and are each an additional 566 glyphs, which should fit within the 65,535 unicode font glyph limit given the reported size of `GoNotoCurrent.ttf` .

**Comment by satbyy** [comment]
Seems the documentation is outdated. The [GoNotoAfricaMiddleEast.ttf](https://github.com/satbyy/go-noto-universal/blob/master/categories.sh#L233) actually includes Noto Sans Ethiopian, plus all those included in Chapter 19 of the Unicode Standard v15.0.

**Comment by quantum9Innovation** [comment]
Sounds good; I'm going to close this issue. I've also submitted a PR (#57) to update the documentation to mention the Ethiopic Sans font.
