### ISSUE TITLE
GoNotoCurrent does not support Korean symbols

### ISSUE THREAD

**Issue by user6905** [satbyy/go-noto-universal#58]
I planned to replace the UniFont by GoNotoCurrent for PDF embedding.

This works very well, but I miss the Korean signs in GoNotoCurrent - there are included in GoNotoCJKCore, but GoNotoCJKCore misses several other languages.

Is this an Error?
Or , if not How Can I add Korean signs to GoNotoCurrent.

**Comment by orzogc** [comment]
see https://github.com/satbyy/go-noto-universal/issues/39#issuecomment-1121519606

**Comment by user6905** [comment]
See other Issue about this topic
