### ISSUE TITLE
Noto Sans Nandinagari Regular could not be merged

### ISSUE THREAD

**Issue by satbyy** [satbyy/go-noto-universal#6]
Currently fonttools doesn't support merging when one of the inputs has different tables not present in the other. In the following example, NotoSans-Regular doesn't have `vmtx`.

```
pyftmerge --verbose NotoSansNandinagari-Regular.ttf  NotoSans-Regular.ttf
Merging 'cmap'.
Merged 'cmap'.
Merging 'GSUB'.
Merged 'GSUB'.
Merging 'GDEF'.
Merged 'GDEF'.
Merging 'head'.
Merged 'head'.
Merging 'cvt '.
Merged 'cvt '.
Merging 'gasp'.
Merged 'gasp'.
Merging 'DSIG'.
Don't know how to merge 'DSIG'.
Dropped 'DSIG'.
Merging 'loca'.
Merging 'vmtx'.
Traceback (most recent call last):
  File "/home/ubuntu/projects/go-noto-universal/venv_fonty/bin/pyftmerge", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/projects/go-noto-universal/venv_fonty/lib/python3.8/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/ubuntu/projects/go-noto-universal/venv_fonty/lib/python3.8/site-packages/fontTools/merge.py", line 1276, in main
    font = merger.merge(fontfiles)
  File "/home/ubuntu/projects/go-noto-universal/venv_fonty/lib/python3.8/site-packages/fontTools/merge.py", line 1097, in merge
    table = clazz(tag).merge(self, tables)
  File "/home/ubuntu/projects/go-noto-universal/venv_fonty/lib/python3.8/site-packages/fontTools/merge.py", line 156, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/home/ubuntu/projects/go-noto-universal/venv_fonty/lib/python3.8/site-packages/fontTools/merge.py", line 1154, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/home/ubuntu/projects/go-noto-universal/venv_fonty/lib/python3.8/site-packages/fontTools/merge.py", line 88, in sumDicts
    d.update(item)
TypeError: 'NotImplementedType' object is not iterable
```

Above is with fonttools 4.28.3

**Comment by satbyy** [comment]
Font merging succeeds with fonttools/fonttools#2473 when Noto Sans Regular is the first argument and vmtx is dropped explicitly (with Nandinagari as first argument, fails with above error):

```
fonttools merge --verbose --drop-tables+=vhea,vmtx \
    NotoSans-Regular.ttf  NotoSansNandinagari-Regular.ttf  

Merging 'cmap'.
Merged 'cmap'.
Merging 'GSUB'.
Merged 'GSUB'.
Merging 'cvt '.
Merged 'cvt '.
Merging 'maxp'.
Merged 'maxp'.
Merging 'DSIG'.
Don't know how to merge 'DSIG'.
Dropped 'DSIG'.
Merging 'name'.
Merged 'name'.
Merging 'post'.
Merged 'post'.
Merging 'gasp'.
Merged 'gasp'.
Merging 'GPOS'.
Merged 'GPOS'.
Merging 'prep'.
Merged 'prep'.
Merging 'hmtx'.
Merged 'hmtx'.
Merging 'STAT'.
Don't know how to merge 'STAT'.
Dropped 'STAT'.
Merging 'OS/2'.
Merged 'OS/2'.
Merging 'gasp'.
Merged 'gasp'.
```

However, the resulting glyphs are erroneous and shifted to the right:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/17479988/146215619-325df8c1-f00c-45c2-9513-e871b0dce179.png">

Test sequence: 𑦮𑧖𑧌𑧠𑦼

**Comment by dscorbett** [comment]
When I try it, both NotoSansNandinagari-Regular.ttf and merged.ttf produce this output.
```
[Ka.Nnagari=0+848|MatraR.Nnagari=0@-273,0+0|SsaNna.Nnagari=2+725]
```
![𑦮𑧖𑧌𑧠𑦼](https://user-images.githubusercontent.com/1124347/146269005-f52cce74-6acf-4d7d-a857-a729ea471ce8.png)
That’s different from the expected output in your last comment. How did you generate that image?

**Comment by satbyy** [comment]
@dscorbett  Ah, I just tried it in Libreoffice. Yours is certainly correct. It is very similar to Devanagari कृष्ण (as it should be). Which application did you use?

**Comment by dscorbett** [comment]
I used hb-view, HarfBuzz’s viewing utility. It should work in anything that uses HarfBuzz, including Chrome, Firefox, and LibreOffice.

**Comment by satbyy** [comment]
It seems that the cached Dogra font in git repo ([`cached_fonts/NotoSerifDogra-Regular.ttf`](https://github.com/satbyy/go-noto-universal/blob/9dbd376/cached_fonts/NotoSerifDogra-Regular.ttf)) can be removed once fonttools/fonttools#2473 is resolved. Otherwise, it currently displays the same error msg as above for Nandinagari.

**Comment by satbyy** [comment]
Hmm. I was too quick in closing the issue.
