### ISSUE TITLE
Font Name with "Noto" allowed by OFL???

### ISSUE THREAD

**Issue by user6905** [satbyy/go-noto-universal#65]
Hello,

if I read the OFL FAQs correctly, I think to use "Noto" in a Font Name is not allowed.
May ist be recommended to use a different artificial name for your fonts?
Even if I personally like the link to Noto in the name, I think that can make problems with the license and Google.

Question: 5.4 Am I not allowed to use any part of the Reserved Font Names?
You may not use individual words from the Reserved Font Names, but you would be allowed to use parts of words, as long as you do not use any word from the Reserved Font Names entirely. We do not recommend using parts of words because of potential confusion, but it is allowed. For example, if "Foobar" was a Reserved Font Name, you would be allowed to use "Foo" or "bar", although we would not recommend it. Such an unfortunate choice would confuse the users of your fonts as well as make it harder for other designers to contribute.

"Noto is a trademark of Google LLC."

**Comment by satbyy** [comment]
The generated font's copyright is assigned to Google itself, so they can claim ownership as they please. This is clear from Font's metadata / font info.
